### ISSUE TITLE
the snowpack build directory also includes elm module source files

### ISSUE THREAD

**Issue by aszenz** [marc136/snowpack-plugin-elm#8]
Thanks for the library, tried it out on a project everything worked great, only that in the build directory i see that it generates a main.js file from `Main.elm` which is expected but also includes source for other Elm modules, is that intended?.

I expected to see only main.js 

![Screenshot from 2020-12-19 00-16-23](https://user-images.githubusercontent.com/25319264/102649641-8a383400-418f-11eb-8ca0-3433d8dddcb4.png)

**Comment by marc136** [comment]
Oh, right. I forgot about that.
That happens because snowpack copies the files where no direct compilation happens. 
As a first workaround you can run a script after build to delete all `.elm` files from the build folder.

I don't know if snowpack now supports to exclude files from copying that cannot be compiled. I will try to look into that this weekend.

**Comment by Zequez** [comment]
As a workaround, right now I wrote the following:

```js
function excludeEverythingButEntryPoints(entryPoints) {
  return env.NODE_ENV === "development"
    ? []
    : fg
        .sync("src/**/*.elm", {
          ignore: entryPoints.map((v) => `**/${v}`),
        })
        .map((v) => v.replace(/^src\//, "**/"));
}
```

And then on Snowpack config:

```js
{
// ...
exclude: excludeEverythingButEntryPoints(["Main.elm"])
// ...
}
```

**Comment by marc136** [comment]
Thanks for this workaround @Zequez, I added it to the README and will close this issue.

**Comment by cmditch** [comment]
This seems to work fine as well fyi.
```
{
  // ... 
   exclude: ['**/*/*.elm'],
  // ...
}
```
